### ISSUE TITLE
MSVC doesn't recognize ssize_t

### ISSUE THREAD

**Issue by icyfox168168** [MetGang/TccWrapper#1]
Thank you for your work. I found that there are compilation errors in vs 2019. Can you release the complete project version

**Comment by MetGang** [comment]
Thanks for your effort and sorry for late response. I believe the issue was caused by ssize_t type being POSIX standard not available on VS2019. I also fixed my typo-like mistake with function syntax. If there is no further problems I will close this issue.

**Comment by icyfox168168** [comment]
Perfect, thanks for such a beautiful library
