### ISSUE TITLE
Standard detection doesn't work properly on MSVC

### ISSUE THREAD

**Issue by icyfox168168** [MetGang/TccWrapper#3]
Does not support the latest version of vs2022? Choosing to support c + + 20 still doesn't work, and the last version works well

**Comment by MetGang** [comment]
Current version of library on master (at the moment of opening this issue) is not yet a full release (just a preparation/WIP). Please use v1.2.1 release until 2.0 (which probably won't support C++17 anymore) will arrive.

Thank you for reporting issues with VS. It's usually not tested with as frequent as GCC/Clang.

**Comment by MetGang** [comment]
> Does not support the latest version of vs2022? Choosing to support c + + 20 still doesn't work, and the last version works well

Library uses `__cplusplus` macro to determine language version. MSVC by default does not support this macro properly unless compiled with `/Zc:__cplusplus` flag. That's possible user side *fix*. Proper fix involves using `_MSVC_LANG` when it's defined.

Nonetheless, fix is on the way.
