### ISSUE TITLE
Can you increase the way you manage memory yourself?

### ISSUE THREAD

**Issue by icyfox168168** [MetGang/TccWrapper#4]
TCCState* s = tcc_new();

    tcc_set_output_type(s, TCC_OUTPUT_MEMORY);

    if (tcc_compile_string(s, buf) != -1)
    {
        int size = tcc_relocate(s, nullptr);
        if (size > 0)
        {
            void* mem = malloc(size);
            tcc_relocate(s, mem);
            ret = ((uint8_t*)tcc_get_symbol(s,"xxxxxxxxx")) ;
            free(mem);
        }
    }
    tcc_delete(s);

**Comment by MetGang** [comment]
Can you be more specific? TccWrapper follows tcc backend and allows to use auto managed memory (internally by tcc via malloc) or user managed memory. I'm not sure what do you mean.
